const adjectives = [
  'Acéfalo',
  'Amoral',
  'Animal',
  'Anti-democrático',
  'Anti-vacina',
  'Atrasado',
  'Autoritário',
  'Besta',
  'Bestial',
  'Beócio',
  'Bolsonaro',
  'Bozo',
  'Boçal',
  'Cabeça de Bagre',
  'Carniceiro',
  'Chefe de Milícia',
  'Chefe de Rachadinha',
  'Chefe do Gado',
  'Chucro',
  'Chulo',
  'Corrupto',
  'Covarde',
  'Desaforado',
  'Desalmado',
  'Descortês',
  'Desequilibrado',
  'Desgraçado',
  'Desleixado',
  'Despreparado',
  'Desprezível',
  'Enganador',
  'Escabroso',
  'Escroto',
  'Espalhafatoso',
  'Espantalho',
  'Estúpido',
  'Fascista',
  'Frívolo',
  'Fútil',
  'Genocida',
  'Ignorante',
  'Iletrado',
  'Imoral',
  'Impotente',
  'Imprudente',
  'Impróprio',
  'Inapto',
  'Incapaz',
  'Incivil',
  'Inclemente',
  'Incompetente',
  'Inepto',
  'Insensato',
  'Insensível',
  'Insuficiente',
  'Intratável',
  'Inábil',
  'Inóspito',
  'Malcriado',
  'Mentecapto',
  'Mentiroso',
  'Narcisista',
  'Nazista',
  'Negacionista',
  'Néscio',
  'Ogro',
  'Orgulhoso',
  'Pai da Mentira',
  'Palhaço',
  'Pateta',
  'Projeto Fracassado de Ditador',
  'Quadrúpede',
  'Racista',
  'Retrógrado',
  'Rude',
  'Ruminante',
  'Selvagem',
  'Servo de Satã',
  'Soberbo',
  'Sombrio',
  'Tacanho',
  'Tapado',
  'Terraplanista',
  'Tirano',
  'Tolo',
  'Tonto',
  'Tosco',
  'Toupeira',
  'Trambiqueiro',
  'Truculento',
  'Vírus'
];

function getRandomAdjective() {
  return adjectives[Math.floor(Math.random() * adjectives.length)];
}

module.exports = {
  getRandomAdjective
};