name: Post tweet by cron

on:
  schedule:
    - cron: "*/9 * * * *"

permissions:
  contents: read

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_KEY_SECRET: ${{ secrets.CONSUMER_KEY_SECRET }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_CLIENT: ${{ secrets.DB_CLIENT }}

jobs:
  post_tweet:
    name: Tweet will be posted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Use Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
      - name: Execute bot to tweet
        run: npm run bot
